# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-10 10:13
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('mobile_no', models.CharField(max_length=10, unique=True)),
                ('user_type', models.NullBooleanField()),
                ('aadhar', models.CharField(blank=True, max_length=20, null=True)),
                ('crops_subscribed_to', models.CharField(max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Area_Data',
            fields=[
                ('area_num', models.IntegerField(primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('air_quality', models.CharField(max_length=1000)),
                ('water_quality', models.CharField(max_length=1000)),
                ('soil_profile', models.CharField(max_length=1000)),
                ('temperature', models.CharField(max_length=1000)),
                ('vegetation_index', models.CharField(max_length=100)),
                ('crop_prices', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=100)),
                ('soil_profile', models.CharField(max_length=100)),
                ('water_req', models.CharField(max_length=50)),
                ('temp_req', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Crop_Alerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('alert', models.CharField(max_length=100)),
                ('days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='State_translator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(default=None, max_length=50)),
                ('state_language', models.CharField(default=None, max_length=50)),
                ('state_code', models.CharField(default='en', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_text', models.TextField()),
                ('is_read', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
